package com.example.com.criteo.apsalartestapp;

import java.util.ArrayList;
import java.util.List;

import android.location.Location;

import com.mobileapptracker.MATEventItem;

/**
 * This class initialize Criteo parameters. 
 * The parameters can be used in for sending Criteo retargeting events 
 * @param void
 * @return void
 */
public class CriteoDO {	
	//This class defines data object for testing parameters of Criteo retargeting
	
	// Advertiser ID and Conversion key. Thses parameter were generated by MAT
	String m_Advertiser_ID = "appsupportus";  // For API Key
	String m_Conversion_Key = "EIAagUkz";  // For Secret key 
	
	String m_StartApp="6398";
	String m_ViewProduct="6402";
	String m_ViewList="6422";
	String m_ViewCart="6406";
	String m_Purchase="6400";
	String m_Search="6404";
	
	// Countgry code and language
	String m_CountryCode="kr";
	String m_Language="ko";
	
	//Criteo Campaign ID
	String m_CampaignId="12345";
	
	//Date in and Date out
	String m_din="2015-04-03";
	String m_dout="2015-05-01";
	
	//Criteo viewProduct Parameters
	
	List <MATEventItem> m_EventProductItems = null;
	
	//Criteo viewListing Parameters
	MATEventItem m_EventItem1 = null;
	MATEventItem m_EventItem2 = null;
	MATEventItem m_EventItem3 = null;
	
	List <MATEventItem> m_EventListingItems = null;
	
	List <MATEventItem> m_EventViewListItems = null;
	
	//Criteo cn parameter
	Location m_Location = null;
	
	//Criteo Currency parameter
	String m_Currency = "USD";
	
	// Criteo Hashed Email
	String m_HashedEmail = "79892287a68598e188555e56132f92ba";
	
	public CriteoDO() {
		super();
		// TODO Auto-generated constructor stub
		
		// Criteo cn parameter
		this.m_Location = new Location("kr");
		
		
		double price;
		
		// This is Criteo product item_id
		price = 3555.50;
		MATEventItem eventItem1 = new MATEventItem("12766277") 	// This is product ID number
										.withQuantity(1)		// This is the number of product of 12766277
        								.withUnitPrice(price);	// This price is unit price for the product which has 12766277 product id 
		
		price = 479.50;
		MATEventItem eventItem2 = new MATEventItem("11262072")	// This is product ID number
										.withQuantity(10)		// This is the number of product of 11262072
										.withUnitPrice(price);	// This price is unit price for the product which has 11262072 product id 
		
		price = 21.23;
		MATEventItem eventItem3 = new MATEventItem("6987408")	// This is product ID number
										.withQuantity(5)		// This is the number of the product of 6987408
										.withUnitPrice(price);	// This price is unit price for the product which has 6987408 product id 
		

		this.m_EventItem1 = eventItem1;
		this.m_EventItem2 = eventItem2;
		this.m_EventItem3 = eventItem3;
		
		this.m_EventListingItems = new ArrayList<MATEventItem> ();
		this.m_EventListingItems.add(eventItem1);
		this.m_EventListingItems.add(eventItem2);
		this.m_EventListingItems.add(eventItem3);
		
		this.m_EventProductItems = new ArrayList<MATEventItem> ();
		this.m_EventProductItems.add(eventItem1);
		
		//This is for product ID list for ViewListing  // Not working
		this.m_EventViewListItems = new ArrayList<MATEventItem> ();
		
	
		MATEventItem eventItem4 = new MATEventItem("product1111");	// This is product ID number
		eventItem4.toJSON();
		
		MATEventItem eventItem5 = new MATEventItem("product2222");
		eventItem5.toJSON();
		
		MATEventItem eventItem6 = new MATEventItem("product33333");
		eventItem6.toJSON();
										
		this.m_EventViewListItems.add(eventItem4);
		this.m_EventViewListItems.add(eventItem5);
		this.m_EventViewListItems.add(eventItem6);

		
		return;
	}
	
}
